### ISSUE TITLE
No sources

### ISSUE THREAD

**Issue by fjf2002** [viartemev/rabbitmq-kotlin#341]
Using the dependency `com.viartemev:the-white-rabbit:0.0.6`,
the downloaded file `the-white-rabbit-0.0.6-sources.jar` is merely empty (only `META-INF/MANIFEST.MF` is present).

Please supply sources, thank you!

**Comment by reactormonk** [comment]
Android studio still has issues downloading the sources for 0.7.0. This should help: https://issuetracker.google.com/issues/320626494#comment4
